# Generated by Django 4.2.11 on 2026-05-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='FC Dominators', max_length=200)),
                ('established_year', models.IntegerField(default=2010)),
                ('description', models.TextField(default='FC Dominators is a competitive football team focused on discipline, growth, and excellence.')),
                ('mission', models.TextField(default='Develop elite football talent while building character, teamwork, and leadership in every player.')),
                ('executive_director_name', models.CharField(default='Yongama Ngondo', max_length=200)),
                ('executive_director_title', models.CharField(default='Head Coach & Team Executive Director', max_length=200)),
                ('goals_objectives', models.TextField(default='Compete at a high level, improve player development pathways, and build a sustainable winning culture.')),
                ('team_achievements', models.TextField(default='Regional tournament appearances, player promotions, and consistent top-league performances.')),
                ('sponsorship_needs', models.TextField(default='Training equipment, transport support, match-day kits, and youth development funding.')),
                ('joining_cost', models.TextField(default='Contact the team for current registration and monthly contribution fees.')),
                ('address', models.CharField(default='Contact the team for the latest training venue details.', max_length=300)),
                ('phone', models.CharField(default='+27694703626', max_length=20)),
                ('whatsapp_number', models.CharField(default='+27694703626', max_length=20)),
                ('calls_number', models.CharField(default='+27694703626', max_length=20)),
                ('email', models.EmailField(default='info@fcdominators.co.za', max_length=254)),
                ('website', models.URLField(blank=True)),
                ('active_members', models.IntegerField(default=500)),
                ('expert_coaches', models.IntegerField(default=15)),
                ('programs', models.IntegerField(default=25)),
                ('years_of_excellence', models.IntegerField(default=12)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='club/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='club/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Club Info',
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('head_coach', 'Head Coach'), ('assistant_coach', 'Assistant Coach'), ('fitness_coach', 'Fitness & Conditioning Lead'), ('youth_coach', 'Youth Academy Coach')], max_length=50)),
                ('bio', models.TextField()),
                ('experience_years', models.IntegerField()),
                ('certifications', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='coaches/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(choices=[('goalkeeper', 'Goalkeeper'), ('defender', 'Defender'), ('midfielder', 'Midfielder'), ('forward', 'Forward')], max_length=50)),
                ('jersey_number', models.IntegerField()),
                ('bio', models.TextField()),
                ('achievements', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('height', models.CharField(blank=True, max_length=50)),
                ('weight', models.CharField(blank=True, max_length=50)),
                ('photo', models.ImageField(upload_to='players/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['jersey_number'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('age_group', models.CharField(max_length=100)),
                ('schedule', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialOrEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('quote', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
