# Generated by Django 4.2.11 on 2026-05-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('fixture', 'Fixture'), ('result', 'Result')], max_length=20)),
                ('opponent', models.CharField(max_length=200)),
                ('competition', models.CharField(blank=True, max_length=200)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('match_date', models.DateField()),
                ('match_time', models.TimeField(blank=True, null=True)),
                ('is_home', models.BooleanField(default=True)),
                ('goals_for', models.IntegerField(blank=True, null=True)),
                ('goals_against', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-match_date', '-match_time', '-created_at'],
            },
        ),
    ]
